package View;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JScrollPane;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dely
 */
public class Favorit extends javax.swing.JFrame {

    /**
     * Creates new form list
     */
    public Favorit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listCafe = new javax.swing.JList<>();
        cafe = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnWishlist = new javax.swing.JButton();
        btnRev1 = new javax.swing.JButton();
        btnMain = new javax.swing.JButton();
        btnViewWishlist = new javax.swing.JButton();
        wishlist = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listCafe.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jScrollPane1.setViewportView(listCafe);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 520, 600));

        cafe.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cafe.setText("Nama Cafe :");
        getContentPane().add(cafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Alamat       :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Rating        :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 370, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Fasilitas      :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Deskripsi     :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 480, -1, -1));

        btnWishlist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/favorit.png"))); // NOI18N
        btnWishlist.setBorder(null);
        btnWishlist.setBorderPainted(false);
        btnWishlist.setContentAreaFilled(false);
        btnWishlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWishlistActionPerformed(evt);
            }
        });
        getContentPane().add(btnWishlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 770, 60, 70));

        btnRev1.setText("Review");
        btnRev1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRev1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRev1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 780, 170, 50));

        btnMain.setOpaque(false);
        btnMain.setContentAreaFilled(false);
        btnMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainActionPerformed(evt);
            }
        });
        getContentPane().add(btnMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 70));

        btnViewWishlist.setOpaque(false);
        btnViewWishlist.setContentAreaFilled(false);
        btnViewWishlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewWishlistActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewWishlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 15, 60, 60));

        wishlist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Wishlist -12.png"))); // NOI18N
        getContentPane().add(wishlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnWishlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWishlistActionPerformed
        // TODO add your handling code here:
        dispose();
        Review rev = new Review();
        rev.show();
    }//GEN-LAST:event_btnWishlistActionPerformed

    private void btnRev1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRev1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRev1ActionPerformed

    private void btnMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainActionPerformed
        // TODO add your handling code here:
        dispose();
        Mainpage main = new Mainpage();
        main.show();
    }//GEN-LAST:event_btnMainActionPerformed

    private void btnViewWishlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewWishlistActionPerformed
        // TODO add your handling code here:
        dispose();
        new Favorit().setVisible(true);
    }//GEN-LAST:event_btnViewWishlistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Favorit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Favorit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Favorit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Favorit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Favorit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMain;
    private javax.swing.JButton btnRev1;
    private javax.swing.JButton btnViewWishlist;
    private javax.swing.JButton btnWishlist;
    private javax.swing.JLabel cafe;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listCafe;
    private javax.swing.JLabel wishlist;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnRev1() {
        return btnRev1;
    }

    public void setBtnRev1(JButton btnRev1) {
        this.btnRev1 = btnRev1;
    }

    public JButton getBtnWishlist() {
        return btnWishlist;
    }

    public void setBtnWishlist(JButton btnWishlist) {
        this.btnWishlist = btnWishlist;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JList<String> getListCafe() {
        return listCafe;
    }

    public void setListCafe(JList<String> listCafe) {
        this.listCafe = listCafe;
    }

    

    
}
