package View;

import Controller.ControllerCafeWishlist;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import Model.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dely
 */
public class ListCafeWishlist extends javax.swing.JFrame {

    /**
     * Creates new form ListCafe
     */
    ControllerCafeWishlist cc;
    
        
    public ListCafeWishlist() {
        initComponents();
        cc = new ControllerCafeWishlist(this);
        cc.registrasi();
        cc.isitable_cari_nama();    
        txtDeskripsi.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cafe = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnRev1 = new javax.swing.JButton();
        btnMain = new javax.swing.JButton();
        btnViewWishlist = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCafe = new javax.swing.JTable();
        txtNamaCafe = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JLabel();
        txtRatinig = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFasilitas = new javax.swing.JLabel();
        btnRev2 = new javax.swing.JButton();
        txtDeskripsi1 = new javax.swing.JScrollPane();
        txtDeskripsi = new javax.swing.JTextArea();
        btnRefresh = new javax.swing.JButton();
        list = new javax.swing.JLabel();
        txtIdCafe = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cafe.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cafe.setText("Nama Cafe :");
        getContentPane().add(cafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Alamat       :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Rating        :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 370, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Fasilitas      :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Deskripsi     :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 480, -1, -1));

        btnRev1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Review button.png"))); // NOI18N
        btnRev1.setBorder(null);
        btnRev1.setContentAreaFilled(false);
        btnRev1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRev1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRev1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 760, 240, 70));

        btnMain.setOpaque(false);
        btnMain.setContentAreaFilled(false);
        btnMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainActionPerformed(evt);
            }
        });
        getContentPane().add(btnMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 70));

        btnViewWishlist.setOpaque(false);
        btnViewWishlist.setContentAreaFilled(false);
        btnViewWishlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewWishlistActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewWishlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 15, 60, 60));

        tableCafe.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        tableCafe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama Cafe", "Alamat", "Fasilitas"
            }
        ));
        tableCafe.setRowHeight(45);
        tableCafe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCafeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableCafe);
        if (tableCafe.getColumnModel().getColumnCount() > 0) {
            tableCafe.getColumnModel().getColumn(0).setHeaderValue("Nama Cafe");
            tableCafe.getColumnModel().getColumn(1).setHeaderValue("Alamat");
            tableCafe.getColumnModel().getColumn(2).setHeaderValue("Fasilitas");
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        txtNamaCafe.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtNamaCafe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtNamaCafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 260, 420, 40));

        txtAlamat.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtAlamat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 320, 420, 40));

        txtRatinig.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtRatinig.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtRatinig, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 370, 420, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Navbar.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtFasilitas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtFasilitas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtFasilitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 420, 420, 40));

        btnRev2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Review button (1).png"))); // NOI18N
        btnRev2.setBorder(null);
        btnRev2.setContentAreaFilled(false);
        btnRev2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRev2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRev2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 760, 240, 70));

        txtDeskripsi.setColumns(20);
        txtDeskripsi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtDeskripsi.setRows(5);
        txtDeskripsi.setBorder(null);
        txtDeskripsi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDeskripsiFocusLost(evt);
            }
        });
        txtDeskripsi.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                txtDeskripsiComponentShown(evt);
            }
        });
        txtDeskripsi1.setViewportView(txtDeskripsi);

        getContentPane().add(txtDeskripsi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 480, 420, 250));

        btnRefresh.setOpaque(false);
        btnRefresh.setContentAreaFilled(false);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, 70, 70));

        list.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        list.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Wishlist -12.png"))); // NOI18N
        list.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(list, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtIdCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdCafeActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdCafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 210, 110, -1));
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 30, 20, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRev1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRev1ActionPerformed
        // TODO add your handling code here:
        Review rev = new Review();
        rev.show();
    }//GEN-LAST:event_btnRev1ActionPerformed

    private void btnMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainActionPerformed
        // TODO add your handling code here:
        dispose();
        Mainpage main = new Mainpage();
        main.show();
    }//GEN-LAST:event_btnMainActionPerformed

    private void btnViewWishlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewWishlistActionPerformed
        // TODO add your handling code here:
        dispose();
        new ListCafeWishlist().setVisible(true);
    }//GEN-LAST:event_btnViewWishlistActionPerformed

    private void tableCafeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCafeMouseClicked
        // TODO add your handling code here:
        cc.isitextfield(tableCafe.getSelectedRow());
        cc.getrate();
//        int barisTerpilih = tableCafe.getSelectedRow();
//        String namaCafe = (String) tableCafe.getValueAt(barisTerpilih, 0);
//        txtIdCafe.setText(namaCafe);

    }//GEN-LAST:event_tableCafeMouseClicked

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void txtIdCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdCafeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtIdCafeActionPerformed

    private void txtDeskripsiComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtDeskripsiComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeskripsiComponentShown

    private void txtDeskripsiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDeskripsiFocusLost
        // TODO add your handling code here:
        txtDeskripsi.setEditable(false);
    }//GEN-LAST:event_txtDeskripsiFocusLost

    private void btnRev2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRev2ActionPerformed
        // TODO add your handling code here:
        
        cc.Delete();
        dispose();
        new ListCafeWishlist().setVisible(true);
    }//GEN-LAST:event_btnRev2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListCafeWishlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListCafeWishlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListCafeWishlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListCafeWishlist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListCafeWishlist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMain;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRev1;
    private javax.swing.JButton btnRev2;
    private javax.swing.JButton btnViewWishlist;
    private javax.swing.JLabel cafe;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel list;
    private javax.swing.JTable tableCafe;
    private javax.swing.JLabel txtAlamat;
    private javax.swing.JTextArea txtDeskripsi;
    private javax.swing.JScrollPane txtDeskripsi1;
    private javax.swing.JLabel txtFasilitas;
    public static javax.swing.JTextField txtIdCafe;
    private javax.swing.JLabel txtNamaCafe;
    private javax.swing.JLabel txtRatinig;
    private javax.swing.JTextField txtemail;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnMain() {
        return btnMain;
    }

    public void setBtnMain(JButton btnMain) {
        this.btnMain = btnMain;
    }

    public JButton getBtnRefresh() {
        return btnRefresh;
    }

    public void setBtnRefresh(JButton btnRefresh) {
        this.btnRefresh = btnRefresh;
    }

    public JButton getBtnRev1() {
        return btnRev1;
    }

    public void setBtnRev1(JButton btnRev1) {
        this.btnRev1 = btnRev1;
    }

    public JButton getBtnViewWishlist() {
        return btnViewWishlist;
    }

    public void setBtnViewWishlist(JButton btnViewWishlist) {
        this.btnViewWishlist = btnViewWishlist;
    }

    public JLabel getCafe() {
        return cafe;
    }

    public void setCafe(JLabel cafe) {
        this.cafe = cafe;
    }

    public JTable getTableCafe() {
        return tableCafe;
    }

    public void setTableCafe(JTable tableCafe) {
        this.tableCafe = tableCafe;
    }

    public JLabel getTxtAlamat() {
        return txtAlamat;
    }

    public void setTxtAlamat(JLabel txtAlamat) {
        this.txtAlamat = txtAlamat;
    }

    public JTextArea getTxtDeskripsi() {
        return txtDeskripsi;
    }

    public void setTxtDeskripsi(JTextArea txtDeskripsi) {
        this.txtDeskripsi = txtDeskripsi;
    }

    public JScrollPane getTxtDeskripsi1() {
        return txtDeskripsi1;
    }

    public void setTxtDeskripsi1(JScrollPane txtDeskripsi1) {
        this.txtDeskripsi1 = txtDeskripsi1;
    }


    public JLabel getTxtFasilitas() {
        return txtFasilitas;
    }

    public void setTxtFasilitas(JLabel txtFasilitas) {
        this.txtFasilitas = txtFasilitas;
    }

    public static JTextField getTxtIdCafe() {
        return txtIdCafe;
    }

    public static void setTxtIdCafe(JTextField txtIdCafe) {
        ListCafeWishlist.txtIdCafe = txtIdCafe;
    }

    public JLabel getTxtNamaCafe() {
        return txtNamaCafe;
    }

    public void setTxtNamaCafe(JLabel txtNamaCafe) {
        this.txtNamaCafe = txtNamaCafe;
    }

    public JLabel getTxtRatinig() {
        return txtRatinig;
    }

    public void setTxtRatinig(JLabel txtRatinig) {
        this.txtRatinig = txtRatinig;
    }

    public JTextField getTxtemail() {
        return txtemail;
    }

    public void setTxtemail(JTextField txtemail) {
        this.txtemail = txtemail;
    }

    

    
    

    

    
}
