/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import View.Login;
import javax.swing.JTextField;
import Controller.ControllerProfil;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author Dely
 */
public final class Profil extends javax.swing.JFrame {

    private  int id_user;

    /**
     * Creates new form Profil
     */
    ControllerProfil cb;
    public Profil()  {
        
        initComponents();
        txtEmail.setEditable(false);
        
        cb = new ControllerProfil(this);
        //cb.registrasi();
        txtEmail.setText(Login.txtEmail.getText());
        String email = Login.txtEmail.getText();
        cb.isitextfield();

        // Buat query untuk mencari nama berdasarkan email_user
        
//        try{
//            Class.forName("com.mysql.cj.jdbc.Driver");
//
//                    // Buat koneksi ke database
//            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbkemanakita", "root", "");
//            String query = "SELECT nama_user FROM user WHERE email_user = ?";
//                    // Buat statement untuk query login
//            PreparedStatement statement = conn.prepareStatement(query);
//
//                    // Set parameter query
//            statement.setString(1, email);  
// 
//
//                    // Eksekusi query
//            PreparedStatement ps = conn.prepareStatement(query);
//
//                    // Cek apakah email dan password valid
//            // Set parameter email_user
//            ps.setString(1, email);
//
//            // Eksekusi query
//            ResultSet rs = ps.executeQuery();
//
//            // Jika ada hasil
//            if (rs.next()) {
//                // Set nama_user ke jtextfield
//                txtNama.setText(rs.getString("nama_user"));
//            }else{
//                        // Tampilkan pesan error
//                JOptionPane.showMessageDialog(null, "Email atau password salah!");
//            }
//        }catch(Exception e){
//           System.out.println("Error!" + e.getMessage()); 
//        }
        
        
    }
        
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNama = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtKoSandi = new javax.swing.JPasswordField();
        txtSandi = new javax.swing.JPasswordField();
        btnMain = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNama.setBackground(new java.awt.Color(242, 242, 242));
        txtNama.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtNama.setText("Nama");
        txtNama.setBorder(null);
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, 350, 50));

        txtEmail.setBackground(new java.awt.Color(242, 242, 242));
        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtEmail.setText("Email");
        txtEmail.setBorder(null);
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 600, 350, 50));

        txtKoSandi.setBackground(new java.awt.Color(242, 242, 242));
        txtKoSandi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtKoSandi.setText("Konfirmasi Sandi");
        txtKoSandi.setBorder(null);
        txtKoSandi.setEchoChar('\u0000');
        txtKoSandi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtKoSandiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtKoSandiFocusLost(evt);
            }
        });
        getContentPane().add(txtKoSandi, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 780, 360, 50));

        txtSandi.setBackground(new java.awt.Color(242, 242, 242));
        txtSandi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtSandi.setText("Sandi Baru");
        txtSandi.setBorder(null);
        txtSandi.setEchoChar('\u0000');
        txtSandi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSandiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSandiFocusLost(evt);
            }
        });
        getContentPane().add(txtSandi, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 690, 360, 50));

        btnMain.setOpaque(false);
        btnMain.setContentAreaFilled(false);
        btnMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMainActionPerformed(evt);
            }
        });
        getContentPane().add(btnMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 60));

        btnLogout.setOpaque(false);
        btnLogout.setContentAreaFilled(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 850, 150, 50));

        btnSave.setOpaque(false);
        btnSave.setContentAreaFilled(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 860, 150, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Profile -5.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        dispose();
        new MainpageAnon().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMainActionPerformed
        // TODO add your handling code here:
        dispose();
        new Mainpage().setVisible(true);
    }//GEN-LAST:event_btnMainActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        cb.updatenama();
        dispose();
        new Profil().setVisible(true);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtSandiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSandiFocusGained
        // TODO add your handling code here:
        if(txtSandi.getText().equals("Sandi Baru")){
            txtSandi.setText(null);
            txtSandi.requestFocus();
            txtSandi.setEchoChar('*');
                
        }
    }//GEN-LAST:event_txtSandiFocusGained

    private void txtSandiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSandiFocusLost
        // TODO add your handling code here:
        if(txtSandi.getText().length()==0){
           txtSandi.setText("Sandi Baru");
       }
    }//GEN-LAST:event_txtSandiFocusLost

    private void txtKoSandiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKoSandiFocusGained
        // TODO add your handling code here:
        if(txtKoSandi.getText().equals("Konfirmasi Sandi")){
            txtKoSandi.setText(null);
            txtKoSandi.requestFocus();
            txtKoSandi.setEchoChar('*');
                
        }
    }//GEN-LAST:event_txtKoSandiFocusGained

    private void txtKoSandiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKoSandiFocusLost
        // TODO add your handling code here:
        if(txtKoSandi.getText().length()==0){
           txtKoSandi.setText("Konfirmasi Sandi");
       }
    }//GEN-LAST:event_txtKoSandiFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMain;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtKoSandi;
    private javax.swing.JTextField txtNama;
    private javax.swing.JPasswordField txtSandi;
    // End of variables declaration//GEN-END:variables
    public String getIdUser(){
        return Integer.toString(id_user);
    }

    public int getId_user() {
        return id_user;
    }

    public void setId_user(int id_user) {
        this.id_user = id_user;
    }

    public JTextField getTxtEmail() {
        return txtEmail;
    }

    public void setTxtEmail(JTextField txtEmail) {
        this.txtEmail = txtEmail;
    }


    public JTextField getTxtNama() {
        return txtNama;
    }

    public void setTxtNama(JTextField txtNama) {
        this.txtNama = txtNama;
    }

    public JPasswordField getTxtKoSandi() {
        return txtKoSandi;
    }

    public void setTxtKoSandi(JPasswordField txtKoSandi) {
        this.txtKoSandi = txtKoSandi;
    }

    public JPasswordField getTxtSandi() {
        return txtSandi;
    }

    public void setTxtSandi(JPasswordField txtSandi) {
        this.txtSandi = txtSandi;
    }

    
    
}
