/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerMitraRegis;
import static Koneksi.koneksi_db.connection;
import java.awt.Font;
import java.awt.Color;
import java.sql.*;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Dely
 */
public class RegisMitra extends javax.swing.JFrame {

    /**
     * Creates new form Regis
     */
    ControllerMitraRegis cb;
    public RegisMitra() {
        initComponents();
        cb = new ControllerMitraRegis(this);
        cb.registrasi();
        pageRegis.setFocusable(true);
            
    }
    
    public void addregis(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.PLAIN);
        textField.setFont(font);
        textField.setForeground(Color.gray);
    }
    public void removeregis(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(Font.PLAIN);
        textField.setFont(font);
        textField.setForeground(Color.black);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtEmail = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        btnRegistrasi = new javax.swing.JButton();
        btnMasuk = new javax.swing.JButton();
        txtkonfirmasi = new javax.swing.JPasswordField();
        txtsandi = new javax.swing.JPasswordField();
        pageRegis = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmail.setBackground(new java.awt.Color(242, 242, 242));
        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEmail.setText("alamat Email");
        txtEmail.setAutoscrolls(false);
        txtEmail.setBorder(null);
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 360, 60));

        txtUsername.setBackground(new java.awt.Color(242, 242, 242));
        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtUsername.setText("username");
        txtUsername.setAutoscrolls(false);
        txtUsername.setBorder(null);
        txtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsernameFocusLost(evt);
            }
        });
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 360, 60));

        btnRegistrasi.setOpaque(false);
        btnRegistrasi.setContentAreaFilled(false);
        btnRegistrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrasiActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 570, 140, 40));

        btnMasuk.setOpaque(false);
        btnMasuk.setContentAreaFilled(false);
        btnMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasukActionPerformed(evt);
            }
        });
        getContentPane().add(btnMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 650, 110, 30));

        txtkonfirmasi.setBackground(new java.awt.Color(242, 242, 242));
        txtkonfirmasi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtkonfirmasi.setText("Konfirmasi Password");
        txtkonfirmasi.setAutoscrolls(false);
        txtkonfirmasi.setBorder(null);
        txtkonfirmasi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtkonfirmasiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtkonfirmasiFocusLost(evt);
            }
        });
        getContentPane().add(txtkonfirmasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, 360, 60));

        txtsandi.setBackground(new java.awt.Color(242, 242, 242));
        txtsandi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtsandi.setText("Password");
        txtsandi.setAutoscrolls(false);
        txtsandi.setBorder(null);
        txtsandi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtsandiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtsandiFocusLost(evt);
            }
        });
        getContentPane().add(txtsandi, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 360, 60));

        pageRegis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Dialog Box Login.png"))); // NOI18N
        getContentPane().add(pageRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasukActionPerformed
        // TODO add your handling code here:
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_btnMasukActionPerformed

    private void btnRegistrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrasiActionPerformed
        // TODO add your handling code here:
        String fullName, email, Password, query1, cariiduser;
        String SUrl, SUser, SPass;
        SUrl = "jdbc:MySQL://localhost:3306/dbkemanakita";
        SUser = "root";
        SPass = "";
        try {
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(SUrl, SUser, SPass);
            Statement st = con.createStatement();
            if("".equals(txtUsername.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "Full Name is require", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }else if("".equals(txtEmail.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "Email Address is require", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }else if("".equals(txtsandi.getText())){
                JOptionPane.showMessageDialog(new JFrame(), "Password is require", "Error",
                        JOptionPane.ERROR_MESSAGE);
            }else {
            fullName = txtUsername.getText(); 
            email    = txtEmail.getText();
            Password = txtsandi.getText();
            System.out.println(Password);
            
            query1 = "INSERT INTO table_cafe(nama_cafe, alamat_cafe, fasilitas_cafe, Deskripsi , email_cafe, password_cafe)VALUES('"+fullName+"', NULL , NULL , NULL , '"+email+"' , '"+Password+"')";
            
            st.execute(query1);
            JOptionPane.showMessageDialog(null, "New account has been created successfully!");
            }
        }catch(Exception e){
           System.out.println("Error!" + e.getMessage()); 
        }
        
        dispose();
        new MitraPage().setVisible(true);
        /*try{
            cb.registrasi();
            new Login().setVisible(true);
            cb.inserttabel();
            cb.registrasi();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Registrasi Gagal");
            throw e;
        }*/
        

        
    }//GEN-LAST:event_btnRegistrasiActionPerformed

    private void txtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusGained
        // TODO add your handling code here:
        if(txtUsername.getText().equals("username")){
            txtUsername.setText(null);
            txtUsername.requestFocus();
            removeregis(txtUsername);
            
            
        }
    }//GEN-LAST:event_txtUsernameFocusGained

    private void txtUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsernameFocusLost
        // TODO add your handling code here:
        if(txtUsername.getText().length()==0){
           addregis(txtUsername);
           txtUsername.setText("username");
       }
    }//GEN-LAST:event_txtUsernameFocusLost

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        // TODO add your handling code here:
        if(txtEmail.getText().equals("alamat Email")){
            txtEmail.setText(null);
            txtEmail.requestFocus();
            removeregis(txtEmail);      
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        // TODO add your handling code here:
        if(txtEmail.getText().length()==0){
           addregis(txtEmail);
           txtEmail.setText("alamat Email");
       }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtsandiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsandiFocusGained
        // TODO add your handling code here:
        if(txtsandi.getText().equals("Password")){
            txtsandi.setText(null);
            txtsandi.requestFocus();
            txtsandi.setEchoChar('*');
            removeregis(txtsandi);      
        }
    }//GEN-LAST:event_txtsandiFocusGained

    private void txtsandiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsandiFocusLost
        // TODO add your handling code here:
        if(txtsandi.getText().length()==0){
           addregis(txtsandi);
           txtsandi.setText("Password");
       }
    }//GEN-LAST:event_txtsandiFocusLost

    private void txtkonfirmasiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtkonfirmasiFocusGained
        // TODO add your handling code here:
        if(txtkonfirmasi.getText().equals("Konfirmasi Password")){
            txtkonfirmasi.setText(null);
            txtkonfirmasi.requestFocus();
            txtkonfirmasi.setEchoChar('*');
            removeregis(txtkonfirmasi);      
        }
    }//GEN-LAST:event_txtkonfirmasiFocusGained

    private void txtkonfirmasiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtkonfirmasiFocusLost
        // TODO add your handling code here:
        if(txtkonfirmasi.getText().length()==0){
           addregis(txtkonfirmasi);
           txtkonfirmasi.setText("Konfirmasi Password");
       }
    }//GEN-LAST:event_txtkonfirmasiFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisMitra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisMitra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisMitra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisMitra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisMitra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMasuk;
    private javax.swing.JButton btnRegistrasi;
    private javax.swing.JLabel pageRegis;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JPasswordField txtkonfirmasi;
    private javax.swing.JPasswordField txtsandi;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnMasuk() {
        return btnMasuk;
    }

    public void setBtnMasuk(JButton btnMasuk) {
        this.btnMasuk = btnMasuk;
    }

    public JButton getBtnRegistrasi() {
        return btnRegistrasi;
    }

    public void setBtnRegistrasi(JButton btnRegistrasi) {
        this.btnRegistrasi = btnRegistrasi;
    }

    public JLabel getBtnSave() {
        return pageRegis;
    }

    public void setBtnSave(JLabel btnSave) {
        this.pageRegis = btnSave;
    }

    public JTextField getTxtEmail() {
        return txtEmail;
    }

    public void setTxtEmail(JTextField txtEmail) {
        this.txtEmail = txtEmail;
    }

    public JTextField getTxtUsername() {
        return txtUsername;
    }

    public void setTxtUsername(JTextField txtUsername) {
        this.txtUsername = txtUsername;
    }

    public JPasswordField getTxtkonfirmasi() {
        return txtkonfirmasi;
    }

    public void setTxtkonfirmasi(JPasswordField txtkonfirmasi) {
        this.txtkonfirmasi = txtkonfirmasi;
    }

    public JPasswordField getTxtsandi() {
        return txtsandi;
    }

    public void setTxtsandi(JPasswordField txtsandi) {
        this.txtsandi = txtsandi;
    }
    
}
