package View;

import Controller.ControllerReview;
import static View.Login.txtEmail;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import View.ListCafe;
import static View.Login.txtEmail;
import java.awt.BorderLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dely
 */
public class Review extends javax.swing.JFrame {

    /**
     * Creates new form Review
     */
    
    ControllerReview cb;
    public Review(){
        initComponents();
        txtReview.setLineWrap(true);
        txtReview.setWrapStyleWord(true);
        cb = new ControllerReview(this);
        txtNamaCafe.setText(ListCafe.txtIdCafe.getText());
        ///cb.isitable_cari_nama();
        cb.isiTabel();
    }   
//        String v = ListCafe.txtIdCafe.getText();
//        System.out.println(v);
//        String SUrl, SUser, SPass;
//        SUrl = "jdbc:MySQL://localhost:3306/dbkemanakita";
//        SUser = "root";
//        SPass = "";
//        try{
//            Class.forName("com.mysql.cj.jdbc.Driver");
//
//                    // Buat koneksi ke database
//            Connection connection = DriverManager.getConnection(SUrl, SUser, SPass);
//
//                    // Buat statement untuk query
//            String query = "SELECT user.nama_user, review.review FROM review INNER JOIN table_cafe ON review.id_cafe = table_cafe.id_cafe INNER JOIN user ON review.id_user = user.id_user WHERE table_cafe.nama_cafe=?";
//            PreparedStatement statement = connection.prepareStatement(query);
//
//                    // Set parameter query
//            statement.setString(1, v);  
//
//
//                    // Eksekusi query
//            ResultSet resultSet = statement.executeQuery();
//
//                    
//            DefaultTableModel model = new DefaultTableModel();
//            model.addColumn("Nama User");
//            model.addColumn("Review");
//
//            while (resultSet.next()) {
//                String namaUser = resultSet.getString("nama_user");
//                String review = resultSet.getString("review");
//                model.addRow(new Object[]{namaUser, review});
//                }
//
//            TableReview.setModel(model);
//            TableReview.addMouseListener(new MouseAdapter() {
//            public void mouseClicked(MouseEvent e) {
//                int row = TableReview.getSelectedRow();
//                String namaUser = (String) model.getValueAt(row, 0);
//                String review = (String) model.getValueAt(row, 1);
//                txtNamaUser.setText(namaUser);
//                txtReview.setText(review);
//            }
//            }
//            );             
//                        // Tampilkan pesan error
//            
//        }catch(Exception e){
//           System.out.println("Error!" + e.getMessage()); 
//        }
      
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableReview = new javax.swing.JTable();
        btnReview = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnViewWishlist = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtReview = new javax.swing.JTextArea();
        txtNamaUser = new javax.swing.JLabel();
        txtExit = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        txtMain = new javax.swing.JButton();
        txtid = new javax.swing.JLabel();
        txtNamaCafe = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableReview.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        TableReview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "User", "Review"
            }
        ));
        TableReview.setRowHeight(45);
        TableReview.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableReviewMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableReview);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 540, 650));

        btnReview.setText("Add Review");
        btnReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReviewActionPerformed(evt);
            }
        });
        getContentPane().add(btnReview, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 780, 170, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Nama Pengguna    : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 190, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Review                 :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 250, -1, -1));

        btnViewWishlist.setOpaque(false);
        btnViewWishlist.setContentAreaFilled(false);
        btnViewWishlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewWishlistActionPerformed(evt);
            }
        });
        getContentPane().add(btnViewWishlist, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 15, 60, 60));

        txtReview.setColumns(20);
        txtReview.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtReview.setRows(5);
        jScrollPane2.setViewportView(txtReview);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 250, 360, 500));

        txtNamaUser.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtNamaUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtNamaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 180, 360, 50));

        txtExit.setOpaque(false);
        txtExit.setContentAreaFilled(false);
        txtExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExitActionPerformed(evt);
            }
        });
        getContentPane().add(txtExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 10, 80, 70));

        btnRefresh.setOpaque(false);
        btnRefresh.setContentAreaFilled(false);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, 70, 70));

        txtMain.setOpaque(false);
        txtMain.setContentAreaFilled(false);
        txtMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMainActionPerformed(evt);
            }
        });
        getContentPane().add(txtMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 70));
        getContentPane().add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 130, 130, 30));
        getContentPane().add(txtNamaCafe, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, 210, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/Review.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReviewActionPerformed
        // TODO add your handling code here:
        new AddReview().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnReviewActionPerformed

    private void btnViewWishlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewWishlistActionPerformed
        // TODO add your handling code here:
        dispose();
        new Favorit().setVisible(true);
        txtReview.setLineWrap(true);
    }//GEN-LAST:event_btnViewWishlistActionPerformed

    private void txtExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_txtExitActionPerformed

    private void TableReviewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableReviewMouseClicked
        // TODO add your handling code here:
        int row = TableReview.rowAtPoint(evt.getPoint());

        // Dapatkan nama user dan review dari model tabel
        String nama_user = (String) TableReview.getModel().getValueAt(row, 0);
        String review = (String) TableReview.getModel().getValueAt(row, 1);

        // Set nama user dan review ke textfield
        txtNamaUser.setText(nama_user);
        txtReview.setText(review);        
    }//GEN-LAST:event_TableReviewMouseClicked

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void txtMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMainActionPerformed
        // TODO add your handling code here:
        dispose();
  
    }//GEN-LAST:event_txtMainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Review.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Review.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Review.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Review.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Review().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableReview;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnReview;
    private javax.swing.JButton btnViewWishlist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton txtExit;
    private javax.swing.JButton txtMain;
    private javax.swing.JLabel txtNamaCafe;
    private javax.swing.JLabel txtNamaUser;
    private javax.swing.JTextArea txtReview;
    public static javax.swing.JLabel txtid;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnReview() {
        return btnReview;
    }

    public void setBtnReview(JButton btnReview) {
        this.btnReview = btnReview;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getjTable1() {
        return TableReview;
    }

    public void setjTable1(JTable jTable1) {
        this.TableReview = jTable1;
    }

    public JTextArea getTxtReview() {
        return txtReview;
    }

    public void setTxtReview(JTextArea txtReview) {
        this.txtReview = txtReview;
    }

    public JTable getTableReview() {
        return TableReview;
    }

    public void setTableReview(JTable TableReview) {
        this.TableReview = TableReview;
    }

    public JButton getBtnRefresh() {
        return btnRefresh;
    }

    public void setBtnRefresh(JButton btnRefresh) {
        this.btnRefresh = btnRefresh;
    }

    public JLabel getTxtNamaUser() {
        return txtNamaUser;
    }

    public void setTxtNamaUser(JLabel txtNamaUser) {
        this.txtNamaUser = txtNamaUser;
    }

    public JLabel getTxtid() {
        return txtid;
    }

    public void setTxtid(JLabel txtid) {
        this.txtid = txtid;
    }

    public JLabel getTxtNamaCafe() {
        return txtNamaCafe;
    }

    public void setTxtNamaCafe(JLabel txtNamaCafe) {
        this.txtNamaCafe = txtNamaCafe;
    }
    
    
    

    
}
